#!/usr/bin/env bash
# Update word lists from the upstream word-list repo (MIT licensed, see THIRD-PARTY-NOTICES.md)
#   wordle-allowed-guesses_en.txt  - 10,657 guess-only words (never answers)
#   wordle-answers-alphabetical_en.txt - 2,315 curated answer words
# Generates src/words.ts with:
#   WORDS   - union of both lists (12,972): everything a player may guess
#   ANSWERS - the 2,315 answer words: the pool puzzle generation draws from
# Run with: npm run update-words

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
OUT_FILE="$REPO_ROOT/src/words.ts"
BASE_URL="https://raw.githubusercontent.com/erikolsson/wordle-clone/main/Wordle/Resources/English"
ALLOWED_URL="$BASE_URL/wordle-allowed-guesses_en.txt"
ANSWERS_URL="$BASE_URL/wordle-answers-alphabetical_en.txt"

TEMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TEMP_DIR"' EXIT

echo "Fetching allowed guesses from $ALLOWED_URL..."
curl -sfL "$ALLOWED_URL" > "$TEMP_DIR/allowed.txt" || { echo "Error: failed to fetch allowed guesses"; exit 1; }

echo "Fetching answers from $ANSWERS_URL..."
curl -sfL "$ANSWERS_URL" > "$TEMP_DIR/answers.txt" || { echo "Error: failed to fetch answers"; exit 1; }

# Filter: lowercase, alphabetic only, exactly 5 letters, deduplicate, sort
ALLOWED=$(grep -E '^[a-z]{5}$' "$TEMP_DIR/allowed.txt" | sort -u)
ANSWERS=$(grep -E '^[a-z]{5}$' "$TEMP_DIR/answers.txt" | sort -u)

ALLOWED_COUNT=$(echo "$ALLOWED" | wc -l | tr -d ' ')
ANSWERS_COUNT=$(echo "$ANSWERS" | wc -l | tr -d ' ')

if [ "$ALLOWED_COUNT" -lt 10000 ]; then
  echo "Error: got only $ALLOWED_COUNT allowed guesses, expected ~10657"
  exit 1
fi
if [ "$ANSWERS_COUNT" -lt 2000 ]; then
  echo "Error: got only $ANSWERS_COUNT answers, expected ~2315"
  exit 1
fi

UNION=$(printf '%s\n%s\n' "$ALLOWED" "$ANSWERS" | sort -u)
UNION_COUNT=$(echo "$UNION" | wc -l | tr -d ' ')

# Format as TypeScript arrays with proper commas and line breaks
UNION_ARRAY=$(echo "$UNION" | sed "s/.*/  '&',/")
ANSWERS_ARRAY=$(echo "$ANSWERS" | sed "s/.*/  '&',/")

cat > "$OUT_FILE" <<EOF
// Auto-generated by scripts/update-words.sh
// Source: https://github.com/erikolsson/wordle-clone (MIT License, see THIRD-PARTY-NOTICES.md)
//   wordle-allowed-guesses_en.txt ($ALLOWED_COUNT words)
//   wordle-answers-alphabetical_en.txt ($ANSWERS_COUNT words)
// WORDS: every acceptable guess (allowed guesses + answers, $UNION_COUNT words)
// ANSWERS: the $ANSWERS_COUNT curated answer words (fair puzzle pool)

export const WORDS: string[] = [
$UNION_ARRAY
];

export const ANSWERS: string[] = [
$ANSWERS_ARRAY
];
EOF

echo "Updated $OUT_FILE with $UNION_COUNT guessable words ($ANSWERS_COUNT answers)"
