import { Puzzle } from "./types";

// Generated via scripts/generate-h0-diverse.cjs
// 2026-10-02: puzzles #1-40 migrated into the curated answer-word policy;
//   puzzles #41-70 generated fresh from the same pool.

export const PUZZLES: Puzzle[] = [
  { h: ["abate", "outgo", "eerie"], v: ["adore", "actor", "erode"], best: 6 },
  { h: ["begat", "usual", "hedge"], v: ["brush", "gourd", "tulle"], best: 5 },
  { h: ["safer", "elect", "lurch"], v: ["steel", "freer", "retch"], best: 6 },
  { h: ["ideal", "angst", "ester"], v: ["image", "eight", "later"], best: 6 },
  { h: ["jumbo", "ingot", "toast"], v: ["joint", "magma", "octet"], best: 6 },
  { h: ["yeast", "cedar", "throw"], v: ["yacht", "ardor", "threw"], best: 5 },
  { h: ["power", "roomy", "rogue"], v: ["purer", "wrong", "rhyme"], best: 4 },
  { h: ["cocoa", "arena", "knoll"], v: ["crank", "credo", "avail"], best: 5 },
  { h: ["trash", "ennui", "dryly"], v: ["trend", "aunty", "hairy"], best: 6 },
  { h: ["koala", "onion", "kneel"], v: ["kiosk", "afire", "annul"], best: 6 },
  { h: ["wager", "loopy", "zonal"], v: ["waltz", "groin", "royal"], best: 5 },
    { h: ["mucus", "usurp", "hyena"], v: ["mouth", "coupe", "sepia"], best: 6 },
    { h: ["upset", "icily", "exert"], v: ["urine", "slice", "tryst"], best: 6 },
  { h: ["drier", "vicar", "rayon"], v: ["diver", "itchy", "rerun"], best: 5 },
  { h: ["expel", "barge", "weedy"], v: ["elbow", "puree", "leery"], best: 5 },
  { h: ["rider", "swing", "yield"], v: ["raspy", "drive", "rigid"], best: 6 },
    { h: ["fleet", "inert", "yearn"], v: ["fairy", "enema", "titan"], best: 5 },
  { h: ["quack", "apnea", "kayak"], v: ["quark", "annoy", "knack"], best: 5 },
  { h: ["noble", "vaunt", "laden"], v: ["novel", "bound", "eaten"], best: 3 },
  { h: ["crept", "usage", "hater"], v: ["cough", "exalt", "their"], best: 6 },
  { h: ["visor", "livid", "dryer"], v: ["valid", "savoy", "radar"], best: 4 },
  { h: ["onset", "nylon", "elder"], v: ["ounce", "salad", "tenor"], best: 6 },
  { h: ["laugh", "vocal", "reedy"], v: ["liver", "uncle", "holly"], best: 5 },
  { h: ["gulch", "aider", "every"], v: ["grace", "ladle", "hardy"], best: 5 },
  { h: ["heart", "vapid", "needy"], v: ["haven", "apple", "toddy"], best: 5 },
  { h: ["excel", "groan", "ruder"], v: ["eager", "cloud", "lunar"], best: 5 },
  { h: ["using", "ditto", "early"], v: ["undue", "inter", "glory"], best: 6 },
  { h: ["aorta", "truss", "ruddy"], v: ["after", "round", "assay"], best: 6 },
  { h: ["tubal", "crypt", "youth"], v: ["tacky", "bayou", "latch"], best: 6 },
  { h: ["basil", "grown", "liege"], v: ["bagel", "scone", "lance"], best: 6 },
  { h: ["kebab", "arson", "idyll"], v: ["khaki", "bushy", "banal"], best: 6 },
  { h: ["roast", "inane", "obese"], v: ["rhino", "agate", "these"], best: 5 },
  { h: ["caste", "ozone", "hilly"], v: ["cloth", "shoal", "elegy"], best: 5 },
  { h: ["meant", "noose", "eject"], v: ["mange", "arose", "treat"], best: 5 },
  { h: ["juror", "unzip", "terse"], v: ["jaunt", "razor", "rupee"], best: 5 },
    { h: ["cacti", "iliac", "defer"], v: ["cried", "chief", "incur"], best: 6 },
  { h: ["quilt", "elide", "lymph"], v: ["quell", "idiom", "teeth"], best: 5 },
  { h: ["quite", "idiot", "lager"], v: ["quill", "icing", "enter"], best: 5 },
  { h: ["decor", "gruel", "tabby"], v: ["digit", "crumb", "relay"], best: 6 },
  { h: ["night", "drake", "ridge"], v: ["nadir", "grand", "there"], best: 6 },
  { h: ["ahead", "ovate", "total"], v: ["afoot", "enact", "dwell"], best: 6 },
  { h: ["brawl", "opium", "honor"], v: ["broth", "align", "lemur"], best: 5 },
  { h: ["queen", "egret", "earth"], v: ["queue", "error", "notch"], best: 5 },
  { h: ["rebus", "fifty", "tithe"], v: ["refit", "befit", "style"], best: 5 },
  { h: ["hydro", "motto", "nomad"], v: ["human", "datum", "ovoid"], best: 5 },
  { h: ["motif", "deter", "march"], v: ["madam", "tutor", "forth"], best: 6 },
  { h: ["nicer", "roost", "enemy"], v: ["nurse", "chore", "ratty"], best: 6 },
  { h: ["tread", "union", "pygmy"], v: ["trump", "eying", "dandy"], best: 5 },
  { h: ["vowel", "scrap", "abyss"], v: ["vista", "warty", "lupus"], best: 6 },
  { h: ["joker", "inept", "entry"], v: ["juice", "knelt", "retry"], best: 5 },
  { h: ["utter", "cling", "rotor"], v: ["ulcer", "taint", "rigor"], best: 5 },
  { h: ["olden", "naive", "rinse"], v: ["owner", "deign", "niece"], best: 5 },
  { h: ["pedal", "young", "erect"], v: ["payee", "deuce", "light"], best: 5 },
  { h: ["salsa", "rarer", "thyme"], v: ["strut", "lorry", "agree"], best: 5 },
  { h: ["knead", "angle", "event"], v: ["knave", "eagle", "dwelt"], best: 4 },
  { h: ["leech", "vault", "repel"], v: ["lover", "equip", "hotel"], best: 4 },
  { h: ["gaffe", "merit", "aroma"], v: ["gamma", "forgo", "extra"], best: 5 },
  { h: ["widow", "irate", "title"], v: ["waist", "dealt", "where"], best: 5 },
  { h: ["imbue", "north", "cater"], v: ["ionic", "burnt", "ether"], best: 5 },
  { h: ["feast", "revue", "eclat"], v: ["forte", "anvil", "tweet"], best: 6 },
  { h: ["carat", "index", "known"], v: ["clink", "radio", "toxin"], best: 5 },
  { h: ["dirge", "basis", "range"], v: ["debar", "risen", "ensue"], best: 5 },
  { h: ["ember", "trust", "retro"], v: ["eater", "brunt", "ratio"], best: 5 },
  { h: ["horse", "umbra", "exile"], v: ["haute", "rabbi", "elate"], best: 5 },
  { h: ["chaff", "input", "kneed"], v: ["crick", "ample", "fetid"], best: 6 },
  { h: ["joist", "unlit", "thrum"], v: ["joust", "idler", "totem"], best: 4 },
  { h: ["qualm", "alibi", "theme"], v: ["quart", "agile", "maize"], best: 5 },
  { h: ["slain", "other", "kinky"], v: ["spook", "ashen", "nerdy"], best: 6 },
  { h: ["wight", "erase", "kappa"], v: ["wreck", "grasp", "theta"], best: 5 },
  { h: ["reset", "viola", "lapse"], v: ["revel", "sloop", "trace"], best: 5 },
];
