import { Puzzle } from "./types";

// Generated via scripts/generate-h0-diverse.cjs
// 2026-10-02: puzzles #1-40 migrated into the curated answer-word policy;
//   puzzles #41-70 generated fresh from the same pool.

export const PUZZLES: Puzzle[] = [
  { h: ["abate", "outgo", "eerie"], v: ["adore", "actor", "erode"] },
  { h: ["begat", "usual", "hedge"], v: ["brush", "gourd", "tulle"] },
  { h: ["safer", "elect", "lurch"], v: ["steel", "freer", "retch"] },
  { h: ["ideal", "angst", "ester"], v: ["image", "eight", "later"] },
  { h: ["jumbo", "ingot", "toast"], v: ["joint", "magma", "octet"] },
  { h: ["yeast", "cedar", "throw"], v: ["yacht", "ardor", "threw"] },
  { h: ["power", "roomy", "rogue"], v: ["purer", "wrong", "rhyme"] },
  { h: ["cocoa", "arena", "knoll"], v: ["crank", "credo", "avail"] },
  { h: ["trash", "ennui", "dryly"], v: ["trend", "aunty", "hairy"] },
  { h: ["koala", "onion", "kneel"], v: ["kiosk", "afire", "annul"] },
  { h: ["wager", "loopy", "zonal"], v: ["waltz", "groin", "royal"] },
    { h: ["mucus", "usurp", "hyena"], v: ["mouth", "coupe", "sepia"] },
    { h: ["upset", "icily", "exert"], v: ["urine", "slice", "tryst"] },
  { h: ["drier", "vicar", "rayon"], v: ["diver", "itchy", "rerun"] },
  { h: ["expel", "barge", "weedy"], v: ["elbow", "puree", "leery"] },
  { h: ["rider", "swing", "yield"], v: ["raspy", "drive", "rigid"] },
    { h: ["fleet", "inert", "yearn"], v: ["fairy", "enema", "titan"] },
  { h: ["quack", "apnea", "kayak"], v: ["quark", "annoy", "knack"] },
  { h: ["noble", "vaunt", "laden"], v: ["novel", "bound", "eaten"] },
  { h: ["crept", "usage", "hater"], v: ["cough", "exalt", "their"] },
  { h: ["visor", "livid", "dryer"], v: ["valid", "savoy", "radar"] },
  { h: ["onset", "nylon", "elder"], v: ["ounce", "salad", "tenor"] },
  { h: ["laugh", "vocal", "reedy"], v: ["liver", "uncle", "holly"] },
  { h: ["gulch", "aider", "every"], v: ["grace", "ladle", "hardy"] },
  { h: ["heart", "vapid", "needy"], v: ["haven", "apple", "toddy"] },
  { h: ["excel", "groan", "ruder"], v: ["eager", "cloud", "lunar"] },
  { h: ["using", "ditto", "early"], v: ["undue", "inter", "glory"] },
  { h: ["aorta", "truss", "ruddy"], v: ["after", "round", "assay"] },
  { h: ["tubal", "crypt", "youth"], v: ["tacky", "bayou", "latch"] },
  { h: ["basil", "grown", "liege"], v: ["bagel", "scone", "lance"] },
  { h: ["kebab", "arson", "idyll"], v: ["khaki", "bushy", "banal"] },
  { h: ["roast", "inane", "obese"], v: ["rhino", "agate", "these"] },
  { h: ["caste", "ozone", "hilly"], v: ["cloth", "shoal", "elegy"] },
  { h: ["meant", "noose", "eject"], v: ["mange", "arose", "treat"] },
  { h: ["juror", "unzip", "terse"], v: ["jaunt", "razor", "rupee"] },
    { h: ["cacti", "iliac", "defer"], v: ["cried", "chief", "incur"] },
  { h: ["quilt", "elide", "lymph"], v: ["quell", "idiom", "teeth"] },
  { h: ["quite", "idiot", "lager"], v: ["quill", "icing", "enter"] },
  { h: ["decor", "gruel", "tabby"], v: ["digit", "crumb", "relay"] },
  { h: ["night", "drake", "ridge"], v: ["nadir", "grand", "there"] },
  { h: ["ahead", "ovate", "total"], v: ["afoot", "enact", "dwell"] },
  { h: ["brawl", "opium", "honor"], v: ["broth", "align", "lemur"] },
  { h: ["queen", "egret", "earth"], v: ["queue", "error", "notch"] },
  { h: ["rebus", "fifty", "tithe"], v: ["refit", "befit", "style"] },
  { h: ["hydro", "motto", "nomad"], v: ["human", "datum", "ovoid"] },
  { h: ["motif", "deter", "march"], v: ["madam", "tutor", "forth"] },
  { h: ["nicer", "roost", "enemy"], v: ["nurse", "chore", "ratty"] },
  { h: ["tread", "union", "pygmy"], v: ["trump", "eying", "dandy"] },
  { h: ["vowel", "scrap", "abyss"], v: ["vista", "warty", "lupus"] },
  { h: ["joker", "inept", "entry"], v: ["juice", "knelt", "retry"] },
  { h: ["utter", "cling", "rotor"], v: ["ulcer", "taint", "rigor"] },
  { h: ["olden", "naive", "rinse"], v: ["owner", "deign", "niece"] },
  { h: ["pedal", "young", "erect"], v: ["payee", "deuce", "light"] },
  { h: ["salsa", "rarer", "thyme"], v: ["strut", "lorry", "agree"] },
  { h: ["knead", "angle", "event"], v: ["knave", "eagle", "dwelt"] },
  { h: ["leech", "vault", "repel"], v: ["lover", "equip", "hotel"] },
  { h: ["gaffe", "merit", "aroma"], v: ["gamma", "forgo", "extra"] },
  { h: ["widow", "irate", "title"], v: ["waist", "dealt", "where"] },
  { h: ["imbue", "north", "cater"], v: ["ionic", "burnt", "ether"] },
  { h: ["feast", "revue", "eclat"], v: ["forte", "anvil", "tweet"] },
  { h: ["carat", "index", "known"], v: ["clink", "radio", "toxin"] },
  { h: ["dirge", "basis", "range"], v: ["debar", "risen", "ensue"] },
  { h: ["ember", "trust", "retro"], v: ["eater", "brunt", "ratio"] },
  { h: ["horse", "umbra", "exile"], v: ["haute", "rabbi", "elate"] },
  { h: ["chaff", "input", "kneed"], v: ["crick", "ample", "fetid"] },
  { h: ["joist", "unlit", "thrum"], v: ["joust", "idler", "totem"] },
  { h: ["qualm", "alibi", "theme"], v: ["quart", "agile", "maize"] },
  { h: ["slain", "other", "kinky"], v: ["spook", "ashen", "nerdy"] },
  { h: ["wight", "erase", "kappa"], v: ["wreck", "grasp", "theta"] },
  { h: ["reset", "viola", "lapse"], v: ["revel", "sloop", "trace"] },
];
